### PR TITLE
Added notice about XQuartz on OSX

### PR DESCRIPTION
**Pull request by fwartner**

### CODE REVIEW

**Comment by Aluxian** [comment]
Why do you need XQuartz?

**Comment by fwartner** [comment]
While i was trying to install the dependencies via Homebrew, i got informed by my terminal that i have to install this.

**Comment by Aluxian** [comment]
Were you installing wine?

**Comment by fwartner** [comment]
I already had wine installed. But it´s not the problem. While installing the dependencies via Homebrew i got noticed about XQuartz..

**Comment by Aluxian** [comment]
I still don't think this is necessary, even though it's not a big deal...
One last question: when you were told to install XQuartz, did that notice also tell you how to install it (i.e. the exact command to run)?

**Pull request closed without merging**
