### PR TITLE
Fix/performance tweaks

### PR DESCRIPTION
**Pull request by nevercast**
I noticed a high CPU usage for M4D. Doing some profiling, the biggest impacts were setInterval(..., 100). I felt that nothing in Messenger needed to be updated that frequently. So made some tweaks and the performance seems to be significantly better.

* The dispatch loop is summoned when it goes from empty to not empty. It does not run constantly.
* The badge label is only set when it's different from the last time it was set
* The badge label is only checked once per second (setBadgeLabel had the highest CPU usage)

This brings the average CPU usage down from 14% to 1%. 

I don't feel that anything is broken by this, but if users would like to test that the badge label and dispatcher work as expected, that would be appreciated.

### CODE REVIEW

**Comment by nevercast** [comment]
#293 #389 

Let me know if this branch fixes your CPU usage issues. It was draining my laptop also. This should help.

**Comment by Sytten** [comment]
NICE! I'm merging in my fork, if you want to help me PR on it pls!!!!!

**Comment by nevercast** [comment]
@Sytten Just so you are aware. Messenger for Desktop is for sale. The domain for at least $1,500USD. With the motivation that it is bought out and monetised. In the future I can not guarantee that it'll remain open-source. @Aluxian 's intentions are to be done with it and move on to other things. Whomever takes it over could make the decision to close source and sell the software.

If you're interested in taking over the project, You should really contact Alexandru me@aluxian.com

**Comment by nevercast** [comment]
Until the future of M4D is known, I'm closing my PRs.

**Comment by Aluxian** [comment]
Just an FYI for everyone: Messenger for Desktop will **always** remain open source. The intention of selling the domain was a tough decision, but not one I'm completely decided to pursue. After thinking about it for a while, I'm leaning towards not selling it anymore. Whatever happens, I promise this repository will stay open source. Also, I'll issue a "looking for a maintainer" announcement soon.

**Comment by nevercast** [comment]
@Aluxian I'm delighted to hear that you intend it to remain open source indefinitely. Pre-announcement I'd be happy to be a maintainer in the future. I'll keep an eye out for the announcement.

Regards :)

**Comment by Sytten** [comment]
@Aluxian @nevercast Hooooo, well its sad to see you go Aluxian. Meanwhile I will continue to develop the code based on NW.JS. I'm ready to help with the new version based on electron too.

**Comment by nevercast** [comment]
This will automatically close when develop moves in to master. Moving to Release.

**Pull request closed without merging**
