### PR TITLE
Merge nwjs-update in to develop

### LINKED ISSUE #412: Context Menu shows up in incorrect position
On Windows, the context menu shows up in the wrong place. 
Perhaps incorrect parent window context?

### PR DESCRIPTION
**Pull request by nevercast**
Before we merge the `nwjs-update` in to develop, I'm summoning @Sytten to remind me of anything I might've forgotten. 

- [x] Debugging works (When using a remote debugger). Information in Readme
- [x] Popup menus work
- [x] Settings save correctly
- [x] Remember window position (not working yet, do we need it in this branch or wait longer?)
- [x] Logs in and does the messenger thing.
- [ ] Test notifications (not done)
- [x] Still not fixed #412 https://github.com/Aluxian/Facebook-Messenger-Desktop/pull/414#issuecomment-219719833
- [x] #418 
- [x] #419 
- [ ] #420 

Any checks you want to do ?

### CODE REVIEW

**Comment by Sytten** [comment]
Maybe it was fixed with the new proxies, but some settings (those without their own click property) were not saved correctly.
I don't really feel that remembering the window position is a big deal.

**Comment by nevercast** [comment]
Which settings do we need besides window position?

**Comment by nevercast** [comment]
Window position is saved, but cannot be applied due to context issue. I can monkey patch for now and we can sort out an API to talk across contexts in future.

**Comment by Aluxian** [comment]
I had a problem with contexts too -- sometimes, showing a dialog crashed the app. I fixed it with an event emitter afaicr, it's somewhere in the app. Maybe that can fix this too?



--
Alexandru Rosianu Full-Stack Developer aluxian.com | startersquad.com On Tue, May 17, 2016 at 5:29 AM, Josh Lloyd < notifications@github.com [notifications@github.com] > wrote:
Window position is saved, but cannot be applied due to context issue. I can monkey patch for now and we can sort out an API to talk across contexts in future.

**Comment by nevercast** [comment]
Ah yes, the dispatcher. Good thinking.

**Comment by nevercast** [comment]
Further thinking
1) That might not work
2) I might have broken the dispatcher in earlier commits, I've not tested it.

**Comment by nevercast** [comment]
Window positions and settings are working nicely now. Took the dispatcher for a test drive with some online/offline state too.

Notifications seem like they are Chrome's notifications now, no longer native. Interesting.

**Comment by Aluxian** [comment]
I've just tested this, and:

- [ ] right click opens the context menu somewhere outside the app window, bottom left corner of my screen

  image

- [ ] the menu on OS X says "nwjs" instead of "Messenger"

  image

- [ ] also, it'd be great if you could split the "Messenger" menu into several ones

  image

- [ ] shouldn't "close with esc key" be disabled by default? I think the users that want that feature are the minority, not the other way around

That's all for now.

**Comment by nevercast** [comment]
I was sure that the issue regarding the dropdown opening in the wrong position was fixed by https://github.com/Aluxian/Facebook-Messenger-Desktop/pull/414/commits/748f8dfeafdf5d8fb1c44a482fc0e37c20e79ebd 

I will need to debug it on OSX. I might set up an OSX VM.

**Comment by nevercast** [comment]
Sometimes but not always, the program running in Task Manager is also nwjs.exe on Windows, instead of Messenger.exe. Will investigate that: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/418

Close with ESC is also here: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/419

Split menu: https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/420

**Comment by Sytten** [comment]
I removed the context menu for now.

**Comment by Sytten** [comment]
I think we are ready to merge in the dev branch...

**Pull request merged**
