### PR TITLE
update version to v1.3.3

### PR DESCRIPTION
**Pull request by PeterDaveHello**

### CODE REVIEW

**Comment by Aluxian** [comment]
Thanks!

**Comment by PeterDaveHello** [comment]
np

**Comment by bil-elmoussaoui** [comment]
@Aluxian after merging this the application keep asking to update to the last update even if you re using the last one. Hope you are going to release a new deb/exe file with this merged ;) Thanks!

**Comment by PeterDaveHello** [comment]
v1.3.3 already released for days.

**Comment by bil-elmoussaoui** [comment]
@PeterDaveHello  i know and i'm using 1.3.3 but the application keeps asking me to update the app to the last version.

**Comment by PeterDaveHello** [comment]
hmmmm ... I have no problem with that.

**Pull request merged**
