### PR TITLE
Fixing the scrollbar bug on some languages

### PR DESCRIPTION
**Pull request by skyli91**
It should fix this issue:
image

### CODE REVIEW

**Comment by Sytten** [comment]
Good I will test. Can you create a PR on the V1.5.X branch instead? thanks!

**Comment by skyli91** [comment]
Here? https://github.com/Sytten/Facebook-Messenger-Desktop/tree/develop

**Comment by Sytten** [comment]
Here: https://github.com/Aluxian/Facebook-Messenger-Desktop/tree/V1.5.X
Remember, I am the official dev now :P

**Comment by skyli91** [comment]
Done: https://github.com/Aluxian/Facebook-Messenger-Desktop/pull/463

**Pull request closed without merging**
