### PR TITLE
Update dark.css

### PR DESCRIPTION
**Pull request by michalzubkowicz**
Dark theme input bar fix

### CODE REVIEW

**Comment by Marox44** [comment]
Hi, I was really looking forward to try it but unfortunatelly it seems like I cannot build it correctly. 
`gulp pack:win32` is done without errors, but neither the build exe nor the installer version doesn't work - Messenger starts in processes list but the window doesn't show up.

But the same happens when I try to build **master** so it is something wrong with my packages.

----

If you would be able to build Your commit and run it, could You please upload the installer or the files somewhere? I'd really like to try it.
 :smiley:

**Comment by auscompgeek** [comment]
This is… not an update.

**Comment by Marox44** [comment]
Okey :smile: 

Today I was able to build it successfully. Looks quite decent for me. As a workaround works completely fine.

----

This is how it looks:

img1

----

Thanks a lot :wink: I hope the author will fix it soon. It's not a big deal and there was already a several issues raised about it.

**Comment by auscompgeek** [comment]
@Marox44 I am the author. I do not approve of this "update".

**Comment by Sytten** [comment]
Closing

**Pull request closed without merging**
