### PR TITLE
Code migrations for NW.js version 0.13.4

### PR DESCRIPTION
**Pull request by gnanet**
The SSL issue discussed in #374 leads to the latest NW.js, which brought some coding changes, these were applied, also a correction for the position of the context menu had to be done (at least on Ubuntu 12.04)

### CODE REVIEW

**Comment by Sytten** [comment]
I totally agree, I was waiting for the new version to be released and supported by NWBuilder, after my exams I will update my fork!

**Comment by gnanet** [comment]
@Sytten your fork is far ahead, i think ill try my changes on yours, so maybe youll get a pull request from me sooner or later :D

**Comment by Sytten** [comment]
Well I'm currently trying to make nwbuilder work with the new version of NW.JS. When they update the tool, I will be able to release a good version updated. Appreciate your help at any time ;)

**Comment by Sytten** [comment]
Well, I cant start the application with the newest version of nw.
I have this error:
Error: EACCES: permission denied, mkdir '/home/emile/.config/Messenger/Default'
Its related with the jfs plugin from what I see...

**Comment by Sytten** [comment]
This is still needed, because we use the old interface with the new code (that is deprecated).
But the code in the current dev branch (V1.5.X) is not same anymore, so we have to redo most of the work.

**Comment by Sytten** [comment]
Not relevant anymore since the code is now with electron.

**Pull request closed without merging**
